### ISSUE TITLE
there is no package called 'ggcorrplot'

### ISSUE THREAD

**Issue by gok-wolf** [Abson-dev/sdmApp#2]
when trying to plot correlations between variables:
"there is no package called 'ggcorrplot'" ...

i think the package name is wrong.
enjoy your new good package.

**Comment by Abson-dev** [comment]
> when trying to plot correlations between variables:
> "there is no package called 'ggcorrplot'" ...
> 
> i think the package name is wrong.
> enjoy your new good package.

Hi,
I will correct this issue in few minutes!
Thanks

**Comment by Abson-dev** [comment]
> when trying to plot correlations between variables:
> "there is no package called 'ggcorrplot'" ...
> 
> i think the package name is wrong.
> enjoy your new good package.

Hi,
try to install ggcorrplot and try to continue ...
Thank you

**Comment by gok-wolf** [comment]
Thank you, we are waiting for detailed tutorial, if you supply this be sure many will going to want to use this package...
